export const COUNTRIES = [
  { code: 'iq', name: 'Iraq', nameAr: 'العراق' },
  { code: 'sa', name: 'Saudi Arabia', nameAr: 'السعودية' },
  { code: 'ae', name: 'United Arab Emirates', nameAr: 'الإمارات' },
  { code: 'kw', name: 'Kuwait', nameAr: 'الكويت' },
  { code: 'qa', name: 'Qatar', nameAr: 'قطر' },
  { code: 'om', name: 'Oman', nameAr: 'عمان' },
  { code: 'bh', name: 'Bahrain', nameAr: 'البحرين' },
  { code: 'eg', name: 'Egypt', nameAr: 'مصر' },
  { code: 'jo', name: 'Jordan', nameAr: 'الأردن' },
  { code: 'lb', name: 'Lebanon', nameAr: 'لبنان' },
  { code: 'sy', name: 'Syria', nameAr: 'سوريا' },
  { code: 'ps', name: 'Palestine', nameAr: 'فلسطين' },
  { code: 'ma', name: 'Morocco', nameAr: 'المغرب' },
  { code: 'dz', name: 'Algeria', nameAr: 'الجزائر' },
  { code: 'tn', name: 'Tunisia', nameAr: 'تونس' },
  { code: 'ly', name: 'Libya', nameAr: 'ليبيا' },
  { code: 'sd', name: 'Sudan', nameAr: 'السودان' },
  { code: 'ye', name: 'Yemen', nameAr: 'اليمن' },
  { code: 'us', name: 'United States', nameAr: 'الولايات المتحدة' },
  { code: 'gb', name: 'United Kingdom', nameAr: 'المملكة المتحدة' },
  { code: 'fr', name: 'France', nameAr: 'فرنسا' },
  { code: 'de', name: 'Germany', nameAr: 'ألمانيا' },
  { code: 'it', name: 'Italy', nameAr: 'إيطاليا' },
  { code: 'es', name: 'Spain', nameAr: 'إسبانيا' },
  { code: 'tr', name: 'Turkey', nameAr: 'تركيا' },
  { code: 'ru', name: 'Russia', nameAr: 'روسيا' },
  { code: 'cn', name: 'China', nameAr: 'الصين' },
  { code: 'jp', name: 'Japan', nameAr: 'اليابان' },
  { code: 'kr', name: 'South Korea', nameAr: 'كوريا الجنوبية' },
  { code: 'br', name: 'Brazil', nameAr: 'البرازيل' },
];
